# gpc client config
grpc:
  client:
    CallpyServiceGrpc:
      address: 'static://127.0.0.1:50051'
      negotiationType: plaintext

# DataSource Config
spring:
  datasource:
    url: jdbc:sqlite:D:\java_code\grpc_callpy\db\Cad.sqlite
    driver-class-name: org.sqlite.JDBC
    username:
    password:
  web:
    resources:
      static-locations: classpath:/static/
