# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cadDet.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63\x61\x64\x44\x65t.proto\x12\x0b\x43\x61\x64\x44\x65tProto\x1a\x1cgoogle/protobuf/struct.proto\"Z\n\x08Position\x12\x10\n\x08left_top\x18\x01 \x01(\x05\x12\x11\n\tright_top\x18\x02 \x01(\x05\x12\x13\n\x0bleft_bottom\x18\x03 \x01(\x05\x12\x14\n\x0cright_bottom\x18\x04 \x01(\x05\"\x1a\n\tAttribute\x12\r\n\x05value\x18\x01 \x03(\t\"i\n\x07\x44\x65tInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\'\n\x08position\x18\x02 \x01(\x0b\x32\x15.CadDetProto.Position\x12)\n\tattribute\x18\x03 \x01(\x0b\x32\x16.CadDetProto.Attribute\"\"\n\rCadDetRequest\x12\x11\n\torigImage\x18\x01 \x01(\x0c\"_\n\x0e\x43\x61\x64\x44\x65tResponse\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12%\n\x07\x64\x65tInfo\x18\x02 \x03(\x0b\x32\x14.CadDetProto.DetInfo\x12\x13\n\x0bresultImage\x18\x03 \x01(\x0c\x32U\n\rCadDetService\x12\x44\n\x07\x45xecute\x12\x1a.CadDetProto.CadDetRequest\x1a\x1b.CadDetProto.CadDetResponse\"\x00\x42\x1f\n\x0e\x63om.chan.protoB\x0b\x43\x61\x64\x44\x65tProtoP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cadDet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016com.chan.protoB\013CadDetProtoP\000'
  _globals['_POSITION']._serialized_start=59
  _globals['_POSITION']._serialized_end=149
  _globals['_ATTRIBUTE']._serialized_start=151
  _globals['_ATTRIBUTE']._serialized_end=177
  _globals['_DETINFO']._serialized_start=179
  _globals['_DETINFO']._serialized_end=284
  _globals['_CADDETREQUEST']._serialized_start=286
  _globals['_CADDETREQUEST']._serialized_end=320
  _globals['_CADDETRESPONSE']._serialized_start=322
  _globals['_CADDETRESPONSE']._serialized_end=417
  _globals['_CADDETSERVICE']._serialized_start=419
  _globals['_CADDETSERVICE']._serialized_end=504
# @@protoc_insertion_point(module_scope)
