# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CallPy.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x43\x61llPy.proto\x12\x0b\x43\x61llPyProto\x1a\x1cgoogle/protobuf/struct.proto\" \n\rScriptRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\" \n\x0eScriptResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2U\n\rCallPyService\x12\x44\n\x07\x45xecute\x12\x1a.CallPyProto.ScriptRequest\x1a\x1b.CallPyProto.ScriptResponse\"\x00\x42\x1f\n\x0e\x63om.chan.protoB\x0b\x43\x61llPyProtoP\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'CallPy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016com.chan.protoB\013CallPyProtoP\000'
  _globals['_SCRIPTREQUEST']._serialized_start=59
  _globals['_SCRIPTREQUEST']._serialized_end=91
  _globals['_SCRIPTRESPONSE']._serialized_start=93
  _globals['_SCRIPTRESPONSE']._serialized_end=125
  _globals['_CALLPYSERVICE']._serialized_start=127
  _globals['_CALLPYSERVICE']._serialized_end=212
# @@protoc_insertion_point(module_scope)
